import 'descriptors.dart';
import 'doggos.dart';

var players = [
  Doggo(
    name: 'Lucky',
    breed: [Breed.husky],
    breedWeight: [100],
    accessory: [],
    position: Position(x: 100, y: 100),
    motion: Motion(),
    achievementIdIOS: 'finished',
    achievementIdAndroid: 'CdfIhE96aspNWLGSQg',
  ),
  Doggo(
    name: 'Grover',
    breed: [Breed.shepherd],
    breedWeight: [100],
    accessory: [],
    position: Position(x: 150, y: 150),
    motion: Motion(),
    achievementIdIOS: 'finished',
    achievementIdAndroid: 'CdfIhE96aspNWLGSQg',
  ),
  Doggo(
    name: 'Brutus',
    breed: [Breed.chihuahua],
    breedWeight: [100],
    accessory: [],
    position: Position(x: 50, y: 50),
    motion: Motion(),
    achievementIdIOS: 'finished',
    achievementIdAndroid: 'CdfIhE96aspNWLGSQg',
  ),
  Doggo(
    name: 'Jazz',
    breed: [Breed.labrador],
    breedWeight: [100],
    accessory: [],
    position: Position(x: 75, y: 75),
    motion: Motion(),
    achievementIdIOS: 'finished',
    achievementIdAndroid: 'CdfIhE96aspNWLGSQg',
  ),
  Doggo(
    name: 'Max',
    breed: [Breed.pug],
    breedWeight: [100],
    accessory: [],
    position: Position(x: 200, y: 200),
    motion: Motion(),
    achievementIdIOS: 'finished',
    achievementIdAndroid: 'CdfIhE96aspNWLGSQg',
  ),
  Doggo(
    name: 'Tina',
    breed: [Breed.poodle],
    breedWeight: [100],
    accessory: [],
    position: Position(x: 250, y: 250),
    motion: Motion(),
    achievementIdIOS: 'finished',
    achievementIdAndroid: 'CdfIhE96aspNWLGSQg',
  ),
];